# @package _global_

# --- L O S S --- #

loss_coeffs:
  - atom_pos:
    - 1.
    - MSELoss
    - ignore_nan: true
  - atom_pos:
    - 0.1
    - herobm.backmapping.train.InvariantsLoss
    - ignore_nan: true

# --- M E T R I C S --- #

metrics_components:
  - atom_pos:
    - geqtrain.train.RMSDMetric
    - ignore_nan: true

metrics_key: validation_loss
metric_criteria: decreasing

# --- T R A I N I N G --- #

batch_size: 1
validation_batch_size: 1
dataloader_num_workers: 0

max_epochs: 1000
learning_rate: 1.e-4
lr_scheduler_name: ExponentialLR
lr_scheduler_gamma: 0.995

optimizer_name: AdamW
optimizer_params:
  amsgrad: false
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
  weight_decay: 1.e-5

max_gradient_norm: 1.0
gradient_clipping_mode: fixed

dropout: 0.
use_ema: false
use_warmup: true
warmup_epochs: 5

early_stopping_patiences:
  validation_loss: 100

sanitize_gradients: true

# train_idcs: [[0,1,2], [0,1,5,10]]
# val_idcs: [[3,4,5,6]]
# n_train: [3,4]
# n_val: [4]